### ISSUE TITLE
Labels/Tags not working

### ISSUE THREAD

**Issue by theapplegates** [thundermiracle/gatsby-simple-blog#163]
When I make a new tag/label and click on it I get an error message:
Not Found

You just hit a route that doesn&#39;t exist... the sadness.

But your tags in the demo site work, your year tags and the "life" tag in your first post. 
any ideas on how to fix it?
Paul

**Comment by thundermiracle** [comment]
I'm not sure. I'm using this template on [my own blog](https://thundermiracle.com/blog), there's no problem there.
How about changing the existed `life` tag to `your own tag` and see if there's any error to find out the problem?

**Comment by theapplegates** [comment]
Ok, I did some testing. I made a new site since I did not make changes yet, other than the Algolia settings.

It seems only numbers work. 
I changed the Life tag to 222 and it worked. I changed it to "2Life" and it failed. I changed it to "222" and it works again.
In coding does it matter if a tag is a number or text?
I'll test more. I don't have a clue yet.

**Comment by thundermiracle** [comment]
Thanks for your test. It's a bug about `kebabCase`. I'll fix it.

**Comment by theapplegates** [comment]
Works perfect. Thanks for your help.
