### ISSUE TITLE
Can't display image cards in Twitter and Facebook when I share a link from the blog

### ISSUE THREAD

**Issue by WatheqAlshowaiter** [thundermiracle/gatsby-simple-blog#202]
I want a thumbnail image to be displayed in the twitter:card and og:image, to be more attractive to the user to click th link..

I know the key is in the SEO component but how I query a thumbnail of each post be displayed?

Also how I display a static image for these pages: 'blog-index, tags. tag"?

I will be very grateful If you show me how to implement it, or at least some hints and resources to do such thing.

**Comment by thundermiracle** [comment]
I don't think this is the problem of this template. You should read more documentation of GatsbyJS instead. Images can be transformed by GatsbyJS' API.

https://www.gatsbyjs.com/docs/how-to/images-and-media/using-gatsby-plugin-image
