### ISSUE TITLE
ready to be used ?

### ISSUE THREAD

**Issue by jatin69** [thundermiracle/gatsby-simple-blog#36]
Hey @thundermiracle 
I like the tags you've added.
Is this template ready to be used? or should I wait if you have a major change in the pipeline?

**Comment by thundermiracle** [comment]
@jatin69 Yes! I’ve already used it in my personal blog.
I’m planning to extract the hard coding ‘Words’ like ‘tags, home...’ to a config file, 
but no major change in future.
