### ISSUE TITLE
Suggest: Add a list of translations on the post

### ISSUE THREAD

**Issue by davidcostadev** [thundermiracle/gatsby-simple-blog#75]
I suggest add a list of current translation on the head of the post like we have on the https://overreacted.io/how-does-react-tell-a-class-from-a-function/

![Screen Shot 2019-07-22 at 16 52 52](https://user-images.githubusercontent.com/3098556/61660883-4478f280-aca1-11e9-8be7-34116fae9c86.png)

**Comment by thundermiracle** [comment]
Yes, I considered to implement this feature before.
But not everyone is as famous as Dan, an article in multiple languages is not that necessary.

I’m using this boilerplate for different contents in different languages.

So I’m not going to implement this feature right now.
But PR is welcomed!

**Comment by davidcostadev** [comment]
I did some similar on my website, https://davidcosta.com.br/en/I-am-back-again/.
Current, when you click on an article and clique em English and change the language the browser redirect to home, and for the user is not so good.

I'm trying to improve this feature on my website, so I can push it here too.

**Comment by thundermiracle** [comment]
@davidcostadev 
I'm going to implement this feature soon.
